---
- name: Extend partition to VG
  hosts: all
  become: yes
  roles:
    - volume_group_extend
  vars:
    vg_name: your_vg        # Volume Group name
    lv_name: your_lv        # Logical Volume name
    partitions:
     - /dev/sdb1   # Partition to use for LVM
     - /dev/sda1   # Partition to use for LVM
